services:
  postgresql-container:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-container
    environment:
      DB_HOST: postgresql-container
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: postgres

volumes:
  postgres_data:
